### ISSUE TITLE
julia_setup() fails to find Julia v1.0.2 when it's in the path on Windows 10

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaInterop/JuliaCall#75] opened 2018-12-01 21:25 UTC
```julia
> library(JuliaCall)
> julia_setup()
Error in julia_setup() : Julia is not found.
```

but 

```
Microsoft Windows [Version 10.0.17134.407]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Chris>julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.2 (2018-11-08)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

>
```

is just fine from the command line.

**Comment by Non-Contradiction** [comment] 2018-12-01 22:53
I think the problem is from https://github.com/Non-Contradiction/JuliaCall/blob/c0fbcd394dd18937228849f0b1799616206f1299/R/aaa.R#L36-L37
What is the result of `system2("julia", "-E \"try println(JULIA_HOME) catch e println(Sys.BINDIR) end;\"", stdout = TRUE)` from R? 
It should give the folder to the Julia binary.

**Comment by ChrisRackauckas** [comment] 2018-12-02 01:49
```
> system2("julia", "-E \"try println(JULIA_HOME) catch e println(Sys.BINDIR) end;\"", stdout = TRUE)
[1] "C:\\Users\\Chris\\AppData\\Local\\JULIA-~1.2\\bin" "nothing"     
```

The correct folder is

```
C:\Users\Chris\AppData\Local\Julia-1.0.2\bin
```

**Comment by Non-Contradiction** [comment] 2018-12-02 02:56
It seems that the result is correct, which is just the short form.
Then the error is really confusing.
Could you try
```
JULIA_HOME = "C:\\Users\\Chris\\AppData\\Local\\JULIA-~1.2\\bin"
tryCatch(system2(file.path(JULIA_HOME, "julia"),
                         "-E \"try println(JULIA_HOME) catch e println(Sys.BINDIR) end;\"", stdout = TRUE)[1],
                 warning = function(war) {},
                 error = function(err) NULL)
```
in R and see what is returned?

**Comment by ChrisRackauckas** [comment] 2018-12-02 03:39
```
> JULIA_HOME = "C:\\Users\\Chris\\AppData\\Local\\JULIA-~1.2\\bin"
> tryCatch(system2(file.path(JULIA_HOME, "julia"),
+                  "-E \"try println(JULIA_HOME) catch e println(Sys.BINDIR) end;\"", stdout = TRUE)[1],
+          warning = function(war) {},
+          error = function(err) NULL)
[1] "C:\\Users\\Chris\\AppData\\Local\\JULIA-~1.2\\bin"
```

**Comment by Non-Contradiction** [comment] 2018-12-02 05:31
How about
```
JuliaCall:::julia_locate(JULIA_HOME = NULL)
```
or
```
JuliaCall:::julia_locate(JULIA_HOME = "C:\\Users\\Chris\\AppData\\Local\\JULIA-~1.2\\bin")
```
Because the first lines in `julia_setup()` is just (omitting uneccesary logic)
```
JULIA_HOME <- julia_locate(JULIA_HOME)

    if (is.null(JULIA_HOME)) {
        stop("Julia is not found.")
    }
```
and this is the only place that emits the `Julia is not found` error.

**Comment by ChrisRackauckas** [comment] 2018-12-02 05:33
```
> JuliaCall:::julia_locate(JULIA_HOME = NULL)
NULL
> JuliaCall:::julia_locate(JULIA_HOME = "C:\\Users\\Chris\\AppData\\Local\\JULIA-~1.2\\bin")
NULL
```

**Comment by Non-Contradiction** [comment] 2018-12-02 05:50
This is the complete code for `JuliaCall:::julia_locate` except inserting some debugging print:
```
JULIA_HOME = NULL
if (is.null(JULIA_HOME)) {
    JULIA_HOME <- getOption("JULIA_HOME")
}
print(JULIA_HOME)
if (is.null(JULIA_HOME)) {
    JULIA_HOME <- if (Sys.getenv("JULIA_HOME") == "") {
        NULL
    } else{
        Sys.getenv("JULIA_HOME")
    }
}
print(JULIA_HOME)

if (is.null(JULIA_HOME)) {
    ## In macOS, the environment variables, e.g., PATH of a GUI is set by launchctl not the SHELL.
    ## You may need to do bash -l -c "which julia" to determine the path to julia.
    ## This fixes the issue that in macOS, R.app GUI cannot find julia.
    ## Thank @randy3k
    julia_bin <- Sys.which("julia")
    if (julia_bin == "") {
        if (.Platform$OS.type == "unix") {
            julia_bin <- system2("bash", "-l -c 'which julia'", stdout = TRUE)[1]
        } else {
            julia_bin <- "julia"
        }
    }
    print(tryCatch(system2(julia_bin, "-E \"try println(JULIA_HOME) catch e println(Sys.BINDIR) end;\"", stdout = TRUE)[1],
             warning = function(war) {},
             error = function(err) NULL))
}
else {
    print(tryCatch(system2(file.path(JULIA_HOME, "julia"),
                     "-E \"try println(JULIA_HOME) catch e println(Sys.BINDIR) end;\"", stdout = TRUE)[1],
             warning = function(war) {},
             error = function(err) NULL))
}
```
And we could also replace the first line with `JULIA_HOME = "C:\\Users\\Chris\\AppData\\Local\\JULIA-~1.2\\bin"` and run again to see what is the problem.

**Comment by xiaodaigh** [comment] 2019-08-26 03:50
This should be solved once #115 is merged

**Comment by mberat** [comment] 2019-12-05 16:59
Hi,
I'm having a similar issue in MacOSX though, 
I'm using R 3.6.1 with Julia version 1.0.5,
When I run:
`julia <- julia_setup()`
I get:
`Error in julia_setup() : Julia is not found.
In addition: Warning message:
In system2("bash", "-l -c 'which julia'", stdout = TRUE) :
  running command ''bash' -l -c 'which julia'' had status 1
sh: NA: command not found`
I'm also not very knowledgeable about the MacOSX file system etc, so if you could answer in detail I would very much appreciate it. In case you would need it path to my Julia is "/Applications/Julia-1.0.app/Contents/Resources/julia/bin/Julia"

Thanks
Mehmet

**Comment by jakelrich** [comment] 2020-02-17 21:16
@mberat A bit late, but if you remove the "/Julia" from the path it should work. Had the same issue on OS X Catalina and that solved that issue.

**Comment by Lili-619** [comment] 2023-06-29 22:56
I have a lot questions: [1] Julia, JULIA_HOME and BINDIR they have the same direction? For example: "C:/Users/mictl/AppData/Local/Programs/Julia-1.9.1/bin"

**Closed** 2024-11-07 20:49 UTC
